In [1]:
import pandas as pd
print("Pandas está listo para usarse, versión:", pd.__version__) 

Pandas está listo para usarse, versión: 2.2.2


### Ejercicio 1
#### Crear y visualizar un arreglo unidimensional como una estructura Series.

In [2]:
outfitprecio = pd.Series([50, 35, 120], index = ["Camiseta", "Pantalones", "Zapatos"])
outfitprecio

Camiseta       50
Pantalones     35
Zapatos       120
dtype: int64

### Ejercicio 2
#### Convertir un objeto Series a una lista Python.

In [3]:
lista_python = outfitprecio.to_list()
print(lista_python)

[50, 35, 120]


### Ejercicio 3
#### Aplicar las operaciones aritméticas básicas (suma, resta, multiplicación y división) sobre objetos Series.

In [15]:
serie1 = pd.Series([1, 2, 3, 4])
serie2 = pd.Series([3, 4, 3, 4])
print("Series originales:",serie1.values,serie2.values)
print("SUMA:")
#suma = serie1 + serie2
suma = serie1.add(serie2)
print(suma.values)
print("RESTA:")
#resta = serie1 - serie2
resta = serie1.sub(serie2)
print(resta.values)
print("MULTIPLICACION:")
#multi = serie1 * serie2
multi = serie1.mul(serie2)
print(multi.values)
print("DIVISION:")
#divi = serie1 / serie2
divi = serie1.div(serie2)
print(divi.values)

Series originales: [1 2 3 4] [3 4 3 4]
SUMA:
[4 6 6 8]
RESTA:
[-2 -2  0  0]
MULTIPLICACION:
[ 3  8  9 16]
DIVISION:
[0.33333333 0.5        1.         1.        ]


### Ejercicio 4
#### Usar operadores relacionales para comparar objetos Series.

In [30]:
serie4a = pd.Series([2,3,4,5,6,20])
serie4b = pd.Series([1,3,5,20,2,6])
print("Series originales:",serie4a.values,serie4b.values)
print("serie4a > serie4b:")
mayor_que = serie4a > serie4b
#mayor_que = serie4a.gt(serie4b)
print(mayor_que.values)
print("serie4a >= serie4b:")
mayor_oiwa = serie4a >= serie4b
#mayoroiwa_que = serie4a.ge(serie4b)
print(mayor_oiwa.values)
print("serie4a < serie4b:")
menor_que = serie4a < serie4b
#menor_que = serie4a.lt(serie4b)
print(menor_que.values)
print("serie4a <= serie4b:")
menor_oiwa = serie4a <= serie4b
#menor_oiwa = serie4a.le(serie4b)
print(menor_oiwa.values)
print("serie4a == serie4b:")
igual_que = serie4a == serie4b
#igual_que = serie4a.eq(serie4b)
print(igual_que.values)
print("serie4a != serie4b:")
#diff_que = serie4a != serie4b
diff_que = serie4a.ne(serie4b)
print(diff_que.values)

Series originales: [ 2  3  4  5  6 20] [ 1  3  5 20  2  6]
serie4a > serie4b:
[ True False False False  True  True]
serie4a >= serie4b:
[ True  True False False  True  True]
serie4a < serie4b:
[False False  True  True False False]
serie4a <= serie4b:
[False  True  True  True False False]
serie4a == serie4b:
[False  True False False False False]
serie4a != serie4b:
[ True False  True  True  True  True]


### Ejercicio 5
#### Convertir un diccionario Python en un objeto Series.

In [31]:
personas = {
    "nombre": "Domi",
    "edad": 27,
    "ciudad": "Sevilla"
}

seriedicc = pd.Series(personas)
seriedicc

nombre       Domi
edad           27
ciudad    Sevilla
dtype: object

### Ejercicio 6
#### Convertir un arreglo NumPy en un objeto Series.

In [35]:
import numpy as np
arraynumpy = np.array([1,2,3,4,5])
serienumpy = pd.Series(arraynumpy)
serienumpy

0    1
1    2
2    3
3    4
4    5
dtype: int64

### Ejercicio 7
#### Cambiar el tipo de datos de un objeto Series.

In [ ]:
serie7 = pd.Series([1,20,4,80,6], index=["Lunes","Martes","Miercoles","Jueves","Viernes"])
print("serie original:","\n",serie7)
serie7modificada = serie7.astype(float)
print("serie modificando el tipo a float:","\n",serie7modificada)

serie original: 
 Lunes         1
Martes       20
Miercoles     4
Jueves       80
Viernes       6
dtype: int64
serie modificando el tipo: 
 Lunes         1.0
Martes       20.0
Miercoles     4.0
Jueves       80.0
Viernes       6.0
dtype: float64


### Ejercicio 8
#### Convertir un objeto Series con múltiples listas en un único objeto Series.


#### Punto de partida 
#### 0    [Colombia, Perú, Argentina]
#### 1             [Bolivia, Uruguay]
#### 2                        [Chile]
####
#### lista=[ [Colombia, Perú, Argentina], [Bolivia, Uruguay],  [Chile]]
####
#### Objetivo
####
#### 0     Colombia
#### 1         Perú
#### 2    Argentina
#### 3      Bolivia
#### 4      Uruguay
#### 5        Chile
#### dtype: object
#### 
#### Serie=[ Colombia, Perú, Argentina, Bolivia, Uruguay, Chile]
#### Pista: Buscar información sobre el método explode()

In [54]:
lista = pd.Series([["Colombia","Perú","Argentina"],["Bolivia","Uruguay"],["Chile"]])
lista.explode().reset_index(drop=True)
lista2 = lista.explode().reset_index(drop=True)
lista2

0     Colombia
1         Perú
2    Argentina
3      Bolivia
4      Uruguay
5        Chile
dtype: object

### Ejercicio 9
#### Ordenar los valores de un objeto Series con el método sort_values.

In [56]:
serie9 = pd.Series([1,43,6,7,8,20,0])
print("Serie original:","\n",serie9)
print("Serie ordenada:","\n",serie9.sort_values())

Serie original: 
 0     1
1    43
2     6
3     7
4     8
5    20
6     0
dtype: int64
Serie ordenada: 
 6     0
0     1
2     6
3     7
4     8
5    20
1    43
dtype: int64


### Ejercicio 10
#### Agregar datos a un objeto Series existente.

In [77]:
serie10 = pd.Series([[2,3,4,5],[4,5,6,7]])
print("serie sin añadir nada","\n",serie10)
serie10[(serie10.last_valid_index()+1)] = [4,5,10,7]
serie10[(serie10.last_valid_index()+1)] = 4
print("serie con dos filas mas:","\n",serie10)
#print("serie ordenada:","\n",serie10.sort_values())

serie sin añadir nada 
 0    [2, 3, 4, 5]
1    [4, 5, 6, 7]
dtype: object
serie con dos filas mas: 
 0     [2, 3, 4, 5]
1     [4, 5, 6, 7]
2    [4, 5, 10, 7]
3                4
dtype: object
